---
env:
  matrix:
      # Generic
    - CONFIGS="allnoconfig allyesconfig defconfig randconfig randconfig randconfig"
      # A64
    - CONFIGS="orangepi_win_defconfig"
      # H5
    - CONFIGS="orangepi_pc2_defconfig orangepi_win_defconfig orangepi_zero_plus_defconfig"

language: c

install:
  - curl -LSs https://github.com/openrisc/or1k-gcc/releases/download/or1k-5.4.0-20170218/or1k-linux-musl-5.4.0-20170218.tar.xz | tar xJf -
  - export PATH=$PATH:$PWD/or1k-linux-musl/bin

matrix:
  include:
    - addons:
        apt:
          packages:
            - g++-7
            - codespell
          sources:
            - ubuntu-toolchain-r-test
      cache:
        directories:
          - uncrustify
      env:
        - BUILD_TYPE=check-format
        - HOSTCC=gcc-7
      install:
        - |-
          if test -d uncrustify/.git; then
            (cd uncrustify && git fetch -q && git reset -q --hard FETCH_HEAD)
          else
            git clone -q https://github.com/uncrustify/uncrustify
          fi
        - git -C uncrustify rev-parse HEAD
        - sed -i 's/chunk_is_token(next, CT_SEMICOLON))$/!prev \&\& &/'
            uncrustify/src/combine.cpp
        - mkdir -p uncrustify/build
        - (cd uncrustify/build && cmake -DCMAKE_INSTALL_PREFIX=$PWD
            -DCMAKE_C_COMPILER=gcc-7 -DCMAKE_CXX_COMPILER=g++-7 ..)
        - make -C uncrustify/build -j$(nproc)
        - export PATH=$PATH:$PWD/uncrustify/build
      script:
        - make check-format
        - codespell -i 0 -q 4 $(git ls-files)
    - env:
        - BUILD_TYPE=out-of-tree
      script:
        - set -e
        - cd /tmp
        - cp $TRAVIS_BUILD_DIR/Makefile .
        - make SRC=$TRAVIS_BUILD_DIR OBJ=$HOME/build defconfig
        - make SRC=$TRAVIS_BUILD_DIR OBJ=$HOME/build -j$(nproc) V=1 all check
        - or1k-linux-musl-size $HOME/build/scp/scp.elf
        - grep __bss_end $HOME/build/scp/scp.map
        - sha256sum -b $HOME/build/scp/scp.bin

script:
  - |-
    set -e
    for config in ${CONFIGS}; do
      echo ========== begin $config ==========
      make "$config"
      make -j$(nproc) TGT="\$(OBJ)/$config" V=1 scp
      or1k-linux-musl-size build/$config/scp.elf
      grep __bss_end build/$config/scp.map
      sha256sum -b build/$config/scp.bin
      echo ========== end $config ==========
    done
...
